### PR TITLE
Add root hash as option parameters w/ support custom raw transaction for contract interact..

### PR DESCRIPTION
**Pull request by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4**

### CODE REVIEW

**Comment by the729** [comment]
Thank you for the PR. I have some suggestions: 

1. Could you please separate this into 2 PRs? One for configuration, one for submitting raw txns. So that we can discuss them separately. 

2. For the configuration part, we have already discussed in #5 . Also in my understanding, the name `RootHash` should be `GenesisHash` or `GenesisTxnHash` everywhere. Root hash in Libra refers to the root of Merkle tree accumulator, which is updated when each new txn is accumulated. When the world begins, after the genesis txn is submitted, the MT accumulator has only 1 txn. That is when the root hash equals to the genesis txn hash. 

3. For the raw txn part, I'm not sure if gopherJS binding can correctly convert a struct as complex as `types.TransactionPayload` from js to golang. Could you please have a try? Probably you could add an example to submit a p2p transaction with the newly added `submitContractTransaction` API?

**Comment by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [comment]
> Thank you for the PR. I have some suggestions:
> 
> 1. Could you please separate this into 2 PRs? One for configuration, one for submitting raw txns. So that we can discuss them separately.
> 2. For the configuration part, we have already discussed in #5 . Also in my understanding, the name `RootHash` should be `GenesisHash` or `GenesisTxnHash` everywhere. Root hash in Libra refers to the root of Merkle tree accumulator, which is updated when each new txn is accumulated. When the world begins, after the genesis txn is submitted, the MT accumulator has only 1 txn. That is when the root hash equals to the genesis txn hash.
> 3. For the raw txn part, I'm not sure if gopherJS binding can correctly convert a struct as complex as `types.TransactionPayload` from js to golang. Could you please have a try? Probably you could add an example to submit a p2p transaction with the newly added `submitContractTransaction` API?

1. Yes.
2. Okay, will perform basic search and try to understand.
3. Yes. It's failed in gopher-js:

```javascript
Error: cannot internalize types.TransactionPayload.
```

**Comment by the729** [comment]
Since I have pushed several commits yesterday (to fix compatibility with the latest testnet), could you please rebase your branch, so that my commits do not show up?

**Comment by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [comment]
Have rewritten and checked both `NewRawCustomModuleTransaction` and `NewRawCustomScriptTransaction` in browser.
`NewRawCustomModuleTransaction` works as fine, while the `NewRawCustomScriptTransaction` requires a nested enum type that gopher-js can't translate and understand it to javascript.

Result as shown below:

```javascript
Error: cannot internalize types.TransactionArgument
```

Could you please have a different options for constructing a `TxnPayloadScript`'s args and support the arguments passed in gopher-js, if you are available?

**Comment by the729** [comment]
Close. See #4

**Pull request closed without merging**
